
const UP = "up";
const DOWN = "down";
const MALE = "male";
const FEMALE = "female";
const ELEVATOR_UPDATE_INTERVAL_MILLIS = 1000;
const ELEVATOR_MAX_FLOOR = 10;
const ADD_PERSON_INTERVAL_MILLIS = 500;

module.exports = {
    UP: UP,
    DOWN: DOWN,
    MALE: MALE,
    FEMALE: FEMALE,
    ELEVATOR_UPDATE_INTERVAL_MILLIS: ELEVATOR_UPDATE_INTERVAL_MILLIS,
    ELEVATOR_MAX_FLOOR: ELEVATOR_MAX_FLOOR,
    ADD_PERSON_INTERVAL_MILLIS: ADD_PERSON_INTERVAL_MILLIS,
}
